# Generated by Django 4.0.5 on 2022-07-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='nombrepices',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AddField(
            model_name='demande',
            name='surface',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
    ]
